import { useState, useCallback } from "react";
import { useCustomizationsStore } from "../../store/customizationsStore";
import { useGuideStore } from "../../store/guideStore";
import { isTownZone } from "../../data/areas";
import type { VendorRegexEntry } from "../../types";
import styles from "./VendorRegex.module.css";

export function VendorRegex() {
  const vendorRegexes = useCustomizationsStore((s) => s.vendorRegexes);
  const addRegex = useCustomizationsStore((s) => s.addRegex);
  const removeRegex = useCustomizationsStore((s) => s.removeRegex);

  const activePhaseId = useCustomizationsStore((s) => s.activePhaseId);
  const buildPhases = useCustomizationsStore((s) => s.buildPhases);
  const activePhase = buildPhases.find((p) => p.id === activePhaseId);
  const phaseRegexes = activePhase?.regexes ?? [];

  const currentZoneId = useGuideStore((s) => s.currentZoneId);
  const inTown = currentZoneId != null && isTownZone(currentZoneId);

  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [copiedPhaseIdx, setCopiedPhaseIdx] = useState<number | null>(null);
  const [showAddForm, setShowAddForm] = useState(false);
  const [newLabel, setNewLabel] = useState("");
  const [newRegex, setNewRegex] = useState("");

  const handleCopy = useCallback((entry: VendorRegexEntry) => {
    navigator.clipboard.writeText(entry.regex).then(() => {
      setCopiedId(entry.id);
      setTimeout(() => setCopiedId(null), 1500);
    }).catch(() => {
      // Clipboard write failed silently
    });
  }, []);

  const handleCopyPhaseRegex = useCallback((regex: string, idx: number) => {
    navigator.clipboard.writeText(regex).then(() => {
      setCopiedPhaseIdx(idx);
      setTimeout(() => setCopiedPhaseIdx(null), 1500);
    }).catch(() => {
      // Clipboard write failed silently
    });
  }, []);

  function handleSave() {
    const label = newLabel.trim();
    const regex = newRegex.trim();
    if (!label || !regex) return;

    const entry: VendorRegexEntry = {
      id: crypto.randomUUID(),
      label,
      regex,
      enabled: true,
      autoGenerated: false,
    };
    addRegex(entry);
    setNewLabel("");
    setNewRegex("");
    setShowAddForm(false);
  }

  function handleCancel() {
    setNewLabel("");
    setNewRegex("");
    setShowAddForm(false);
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === "Enter") {
      e.preventDefault();
      handleSave();
    } else if (e.key === "Escape") {
      handleCancel();
    }
  }

  const isEmpty = vendorRegexes.length === 0 && phaseRegexes.length === 0;

  return (
    <div className={`${styles.panel} ${inTown ? styles.panelInTown : ""}`}>
      {inTown && (
        <div className={styles.townBadge}>In Town — Check Vendors</div>
      )}

      {phaseRegexes.length > 0 && (
        <ul className={styles.regexList}>
          {phaseRegexes.map((regex, idx) => {
            const isCopied = copiedPhaseIdx === idx;
            return (
              <li
                key={idx}
                className={`${styles.regexRow} ${isCopied ? styles.regexRowCopied : ""}`}
                onClick={() => handleCopyPhaseRegex(regex, idx)}
                role="button"
                tabIndex={0}
                title="Click to copy (from active phase)"
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    handleCopyPhaseRegex(regex, idx);
                  }
                }}
              >
                <span className={styles.regexLabel}>Phase</span>
                <code className={styles.regexCode}>{regex}</code>
                <span className={styles.copyIndicator}>
                  {isCopied ? "Copied!" : "copy"}
                </span>
              </li>
            );
          })}
        </ul>
      )}

      {vendorRegexes.length > 0 && (
        <ul className={styles.regexList}>
          {vendorRegexes.map((entry) => {
            const isCopied = copiedId === entry.id;
            return (
              <li
                key={entry.id}
                className={`${styles.regexRow} ${isCopied ? styles.regexRowCopied : ""}`}
                onClick={() => handleCopy(entry)}
                role="button"
                tabIndex={0}
                title="Click to copy"
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    handleCopy(entry);
                  }
                }}
              >
                <span className={styles.regexLabel}>{entry.label}</span>
                <code className={styles.regexCode}>{entry.regex}</code>
                <span className={styles.copyIndicator}>
                  {isCopied ? "Copied!" : "copy"}
                </span>
                {!entry.autoGenerated && (
                  <button
                    className={styles.removeBtn}
                    title="Remove regex"
                    onClick={(e) => {
                      e.stopPropagation();
                      removeRegex(entry.id);
                    }}
                  >
                    ×
                  </button>
                )}
              </li>
            );
          })}
        </ul>
      )}

      {showAddForm ? (
        <div className={styles.addForm}>
          <input
            className={styles.formInput}
            type="text"
            placeholder="Label (e.g. Life + Res)"
            value={newLabel}
            onChange={(e) => setNewLabel(e.target.value)}
            onKeyDown={handleKeyDown}
            autoFocus
          />
          <input
            className={`${styles.formInput} ${styles.formInputMono}`}
            type="text"
            placeholder="Regex string"
            value={newRegex}
            onChange={(e) => setNewRegex(e.target.value)}
            onKeyDown={handleKeyDown}
          />
          <div className={styles.formActions}>
            <button
              className={styles.saveBtn}
              onClick={handleSave}
              disabled={!newLabel.trim() || !newRegex.trim()}
            >
              Save
            </button>
            <button className={styles.cancelBtn} onClick={handleCancel}>
              Cancel
            </button>
          </div>
        </div>
      ) : (
        <button
          className={styles.addBtn}
          onClick={() => setShowAddForm(true)}
        >
          {isEmpty ? "+ Add Vendor Regex" : "+ Add Regex"}
        </button>
      )}
    </div>
  );
}
