import type { BuildPhase, StepReminder } from "./buildPlan";

export type { BuildPhase, StepReminder };

export interface VendorRegexEntry {
  id: string;
  label: string;
  regex: string;
  enabled: boolean;
  autoGenerated: boolean;
}

export interface InlineNote {
  pageIndex: number;
  stepIndex: number;
  text: string;
}

export interface WatchlistEntry {
  id: string;
  name: string;
  type: "gem" | "item";
  iconPath?: string;
  unlockLevel: number;
}

export interface Customizations {
  buildPhases: BuildPhase[];
  stepReminders: StepReminder[];
  vendorRegexes: VendorRegexEntry[];
  inlineNotes: InlineNote[];
  activePhaseId: string | null;
  watchlist: WatchlistEntry[];
}

export const DEFAULT_CUSTOMIZATIONS: Customizations = {
  buildPhases: [],
  stepReminders: [],
  vendorRegexes: [],
  inlineNotes: [],
  activePhaseId: null,
  watchlist: [],
};

export type { GemEntry as GemData } from "./itemDatabase";
